#!/bin/sh
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2014-03-01 @ 15:45:50
# VER : Version 1b

set -x

# If the user is not root
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2 ; exit 1
fi

# Read in the SSH key
echo "Input the key to be added:"
read key

# Place the key in a temporary file (it's hard to get ssh-keygen
# to read from stdin; <<< works for bash, but is non-posix)
keyfile=$(mktemp /tmp/XXXXX) &&\
echo "$key" > $keyfile

# Generate a fingerprint
fingerprint=$(ssh-keygen -lf $keyfile)

# Check for errors
if [ $(echo "$fingerprint" | egrep -c '(R|D)SA') -eq 0 ]; then
	# Display the fingerprint error and clean up
	echo "Error: $fingerprint"
	rm $keyfile
	exit 1
fi

cd ..

# Add the key to the authorised keys file and clean up
mkdir -p /home/git/.ssh &&\
echo -n "no-agent-forwarding,no-port-forwarding,no-X11-forwarding " >> /home/git/.ssh/authorized_keys &&\
cat $keyfile >> /home/git/.ssh/authorized_keys
rm $keyfile

# Display the fingerprint for reference
echo "Success! Added a key with the following fingerprint:"
echo $fingerprint