#!/bin/sh
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2014-09-02 @ 13:46:03
# VER : Version 1a

# If no project name is given
if [ $# -eq 0 ]; then
    # Display usage and stop
    echo "Usage: addrepo <project.git>" ; exit 1
fi

# Set the project name, adding .git if necessary
project=$(echo "$*" | sed 's/\.git$\|$/.git/i')

[ git ls-remote "${project}" &> /dev/null ] && {
    cd /home/git/repositories/
    git clone --mirror "${project}"

    ## might need
    ## sudo chown -R git:git .

} || {
    echo "[ERROR] Unable to read from '${project}'"; exit 1
}