#!/bin/sh
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2014-09-02 @ 13:46:03
# VER : Version 1a

# local repo test function
function t()
{
    git ls-remote "${1}" &>-
    [ "$?" -ne 0 ] && { 
        return 1 
    } || {
        return 0
    }
}

# If no project name is given
if [ $# -eq 0 ]; then
    # Display usage and stop
    echo "Usage: addrepo <project.git>" ; exit 1
fi

# Set the project name, adding .git if necessary
project=$(echo "$*" | sed 's/\.git$\|$/.git/i')
repo="$(echo "${project}" |awk -NF '/' '{print $(NF)}')"

cd /home/git/repositories/
[ $(t "${project}") -eq 1 ] && {
    git clone --mirror "${project}"

    ## might need
    ## sudo chown -R git:git .

} || {
    echo "[ERROR] Unable to read from '${project}'"; exit 1
}