#!/bin/sh
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2014-03-01 @ 15:45:50
# VER : Version 1b

# If no project name is given
if [ $# -eq 0 ]; then
	# Display usage and stop
	echo "Usage: drop <project.git>" ; exit 1
fi

# Set the project name, adding .git if necessary
project=$(echo "$*" | sed 's/\.git$\|$/.git/i')

dir=/home/git/repositories/"$project"

# Drop the directory
[ -d $dir ] && rm -rf $dir