#!/bin/sh
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2014-03-01 @ 15:45:50
# VER : Version 1b

print_if_bare_repo='
	if "$(git --git-dir="$1" rev-parse --is-bare-repository)" = true
	then
		printf "%s\n" "${1#./}"
	fi
'

find -type d -name "*.git" -exec sh -c "$print_if_bare_repo" -- \{} \; -prune 2>/dev/null
