#!/bin/sh
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2014-09-02 @ 15:28:22
# VER : Version 1a

# If no project name is given
if [ $# -eq 0 ]; then
    # Display usage and stop
    echo "Usage: mirror <project.git> <repository-url>" ; exit 1
fi

# Set the project name, adding .git if necessary
project=$(echo "$1" | sed 's/\.git$\|$/.git/i')

cd /home/git/repositories/

if [ -d  "${project}" ]; then
    cd /tmp && git clone "git@localhost:repositories/${project}" 
    cd "${project}" && git push --mirror -a -t "${project}" "${2}"
fi